core/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from core import views

app_name = 'core'

urlpatterns = [
	path('', views.covid_list, name='covid_list'),
	url(r'^register/$',views.register,name='register'),
	url(r'^user_login/$',views.user_login,name='user_login'),
]

covid19/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    #url(r'^password/$', views.change_password, name='change_password'),
    
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^core/',include('core.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

    path('change_password/', views.change_password, name='change_password'),

    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('covid_list/', views.covid_list, name='covid_list'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
    path('search_estabelecimento/', views.search_estabelecimento, name='search_estabelecimento'),
    path('search_estabelecimento/submit', views.search_estabelecimento_set),
    path('registro_covid/', views.registro_covid, name='registro_covid'),
    path('registro_covid/submit', views.registro_covid_set),
    path('registro_enfermeiro_medico/', views.registro_enfermeiro_medico, name='registro_enfermeiro_medico'),
    path('regulacao/<id>/', views.regulacao, name='regulacao'),
    path('regulacao/<id>/submit', views.regulacao_set),
    path('regulacao_edit/<id>/', views.regulacao_edit, name='regulacao_edit'),
    path('regulacao_edit/<id>/submit', views.regulacao_edit_set),
    path('regulacao_detail/<id>/', views.regulacao_detail, name='regulacao_detail' ),
    path('regulacao_search_estabelecimento/<id>/', views.regulacao_search_estabelecimento, name='regulacao_search_estabelecimento' ),
    path('regulacao_search_estabelecimento/<id>/submit', views.regulacao_search_estabelecimento_set),
    path('search_register/', views.search_register, name='search_register'),
    path('search_between_date/', views.search_between_date, name='search_between_date'),
    path('search_between_date/submit', views.search_between_date_set),
    path('result_search_between_date/', views.result_search_between_date, name='result_search_between_date'),
    path('gerar_relatorios/', views.gerar_relatorios, name='gerar_relatorios'),
    path('gerar_relatorios/submit', views.gerar_relatorios_set),
    path('result_for_relatorios/', views.result_for_relatorios, name='result_for_relatorios'),
    path('status_registro/<id>/', views.status_registro, name='status_registro'),
    path('status_registro/<id>/submit', views.status_registro_set),
    path('remove_registro_covid/<id>/', views.remove_registro_covid, name='remove_registro_covid'),
    path('image_descricao_clinica_alter/<id>/', views.image_descricao_clinica_alter, name='image_descricao_clinica_alter'),
    path('image_descricao_clinica_alter/<id>/submit', views.image_descricao_clinica_alter_set),
    path('image_rx_torax_alter/<id>/', views.image_rx_torax_alter, name='image_rx_torax_alter'),
    path('image_rx_torax_alter/<id>/submit', views.image_rx_torax_alter_set),
    path('image_tc_torax_alter/<id>/', views.image_tc_torax_alter, name='image_tc_torax_alter'),
    path('image_tc_torax_alter/<id>/submit', views.image_tc_torax_alter_set),
    path('regular_registro/<id>/', views.regular_registro, name='regular_registro'),
    path('regular_registro/<id>/submit', views.regular_registro_set),
    path('paciente_atribuir_senha/<id>/', views.paciente_atribuir_senha, name='paciente_atribuir_senha'),
    path('paciente_atribuir_senha/<id>/submit', views.paciente_atribuir_senha_set),
    path('template_censo/', views.template_censo, name='template_censo')
]

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CERH</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% if user.is_authenticated %}
          {% if user.first_name == 'videofonista' or user.first_name == 'enfermeiro' or user.first_name == 'medico' %}
          {%else%}
          <li><a class="navbar-link" href="{% url 'core:register' %}">Registre-se</a></li>
          {%endif%}
          {%endif%}
        
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'core:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/change_password.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save changes</button>
</form>

templates/gerar_relatorios.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
	<title>Relatório de Registro - Casos COVID19</title>
	<link rel="stylesheet" href="">

	<script language="JavaScript" type="text/javascript" src="/static/js/cidades-estados-1.4-utf8.js"></script>


</head>
<body>

	<div class="container" style="border: 2px solid #cccccc; border-radius: 10px">
		<div class="jumbotron">
			<h1>SES COVID - Registro - Casos COVID19</h1>
			<p></p>
		</div>

		<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
		  <ul class="navbar-nav">
		    <li class="nav-item">
		      <a class="nav-link" href="/">Home</a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="/covid_list/">Principal</a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="/search_estabelecimento/">Registrar Caso</a>
		    </li>
		    <!--
		    <li class="nav-item">
		      <a class="nav-link" href="/registro_covid/">Registrar Caso</a>
		    </li>
		-->
		    <li class="nav-item">
		      <a class="nav-link" href="#"></a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link" href="/search_register/">Localizar</a>
		    </li>
		    <li class="nav-item">
		      <a class="nav-link active" href="/gerar_relatorios/">Relatórios</a>
		    </li>
		    <li>
		    	<a class="nav-link" href="/accounts/logout">Sair</a>
		    </li>
		  </ul>
		</nav><br>
		
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-4" style="background-color:;">
					<div style="position: relative; left: 0; top: 20%; width: 100%; text-align: center;">
						<img src="https://docs.google.com/uc?id=1g14C98IyGkVYPNNkoLk20rGYVikptzcC" alt="" style=" background-color: ;width: 70%">
					</div>
				</div>

	      		<div class="col-sm-4" style="">
	      			<div class="col" style="text-align: center;">
	      				<p>GOVERNO DO ESTADO DA PARAÍBA</p>
	      				<p>SECRETARIA DE ESTADO DA SAÚDE</p>
	      				<p></p>
	      				<p><h7><b>Registro de Casos - Perfil {{user.first_name}} - Usuário: <i>{{user}}</i></b></h7></p>
	      			</div>
	      		</div>
	      		<div class="col-sm-4" style="background-color:;">
	      			<div style="position: relative; left: 0; top: 30%; width: 100%; text-align: center;">
	      				<img src="https://docs.google.com/uc?id=11gNpuLZuHBRHHiSFZxcSp5CGlJla1PEw" alt="" style="background-color: ;width: 70%">
	      			</div>
	      		</div>
	      	</div>
	    <br>
		</div>
		<hr />

		<div class="row">
			<div class="col-sm-5"></div>
			<div class="col-sm-3"></div>
			<div class="col-sm-4"></div>
		</div>

		<div class="row">
			<div class="col-sm-5"></div>
			<div class="col-sm-3"><b class="btn btn-secondary btn-sm">Informe data de início e fim</b></div>
			<div class="col-sm-4"></div>
		</div><br />

	<div class="container mt-3">
	  	<form enctype="multipart/form-data" action="submit" method="POST">{% csrf_token %}
	  		<div class="container">
	  			<div class="row">
	  				<div class="col-sm-1"></div>
	  				<div class="col-sm-5">Início
	  					<div class="form-check-inline">
							<input type="date" class="form-control form-control-sm" id="" placeholder="" name="data_inicio" value="" required>
					    </div>
	  				</div>
	  				<div class="col-sm-1"></div>
	  				<div class="col-sm-5">Fim
	  					<div class="form-check-inline">
							<input type="date" class="form-control form-control-sm" id="" placeholder="" name="data_fim" value="" required>
					    </div>
	  				</div>
	  			</div>
	  			
	  		</div>
	  		<br />

	  		<div class="container-fluid" style="text-align: center;">
				<button type="submit" autofocus="autofocus" class="btn btn-primary" style="align-items: center;" id="btn_inserir_paciente">Export to Excel</button>  
	    	</div><br />
	  	</form>
	</div>


<!--
	<table class="table table-hover" style="font-size: 60%">
    <thead>
      <tr>
      	<th>Protocolo</th>
      	<th>Registro CERN</th>
      	<th>Nome</th>
        <th>Idade</th>
        <th>Sexo</th>
        <th>Status</th>
        <th>Município de Residencia</th>
        <th>Estabelecimento de Origem</th>
        <th>Estabelecimento Referencia Covid</th>
        <th>Município do Estabelecimento</th>
        <th>Perfil</th>
        <th>Data</th>
        <th>Comorbidades</th>
        <th>Nível de Atenção</th>
        <th>Tipo de Teste</th>
        <th>Teste Covid</th>
      </tr>
    </thead>
    <tbody>
    	{% for o in regs %}
      <tr>
        <td>{{o.data_notificacao|date:'d/m/Y'}} - {{o.hora_notificacao|time:'H:i'}}</td>
        <td>
        	{% if o.estabelecimento_solicitante == '' or o.estabelecimento_solicitante == None %}
        	<a href="#">{{o.estabelecimento_outro}}</a>
        	{%else%}
        	<a href="#">{{o.estabelecimento_solicitante}}</a>
        	{%endif%}
        </td>
        <td>{{o.nome_paciente}}</td>
        <td>
        	{% if o.idade_paciente == '' or o.idade_paciente == None %}
        	{%else%}
        	{{o.idade_paciente}}
        	{%endif%}
        </td>
        <td style="font-size: 87%">
        	<a href="/regulacao_edit/{{o.id}}">Editar</a>
        	
        	<a href="/regulacao/{{o.id}}/">Regular</a>
        	<a href="/regulacao_detail/{{o.id}}/">Ver</a>
        	
        </td>
      </tr>
      	{% endfor %}
      
    </tbody>
  </table>
-->
  <div style="height: 50px"></div>

		
	</div><br />

	
	<div style="background-color: #e6e6e6;">
		
			<br /><br />
		
	</div>
	
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Bem vindo à CERH!</h1>
    {% if user.is_authenticated %}
        <h3><a href="/covid_list/">Acessar Sistema</a></h3>
    {% else %}
        <h2></h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/list.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
	<title>SES COVID Registro de Casos COVID19</title>
	<link rel="stylesheet" href="">

	<script language="JavaScript" type="text/javascript" src="/static/js/cidades-estados-1.4-utf8.js"></script>

</head>
<body>

	<div class="container" style="border: 2px solid #cccccc; border-radius: 10px">
		<div class="jumbotron">
			<h1>SES COVID - Registro - Casos COVID19</h1>
			<p></p>
		</div>

		<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/covid_list/">Principal</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/search_estabelecimento/">Registrar Caso</a>
            </li>
		    <!--
		    <li class="nav-item">
		      <a class="nav-link" href="/registro_covid/">Registrar Caso</a>
		    </li>
		-->
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/search_register/">Localizar</a>
    </li>
    <li class="nav-item">
      {% if user.first_name == 'videofonista' or user.first_name == 'medico' or user.first_name == 'enfermeiro' %}
      {% else %}
        <a class="nav-link" href="/gerar_relatorios/">Relatórios</a>
      {%endif%}
    </li>
    <li>
     <a class="nav-link" href="/template_censo/">Censo Hospitalar</a>
 </li>
    <li>
     <a class="nav-link" href="/change_password/">Alterar senha</a>
 </li>
 <li>
     <a class="nav-link" href="/accounts/logout">Sair</a>
 </li>
</ul>
</nav><br>

<div class="container-fluid">
 <div class="row">
    <div class="col-sm-4" style="background-color:;">
       <div style="position: relative; left: 0; top: 20%; width: 100%; text-align: center;">
          <img src="https://docs.google.com/uc?id=1g14C98IyGkVYPNNkoLk20rGYVikptzcC" alt="" style=" background-color: ;width: 70%">
      </div>
  </div>

  <div class="col-sm-4" style="">
      <div class="col" style="text-align: center;">
         <p>GOVERNO DO ESTADO DA PARAÍBA</p>
         <p>SECRETARIA DE ESTADO DA SAÚDE</p>
         <p></p>
         <p><h7><b>Registro de Casos - Perfil {{user.first_name}} - Usuário: <i>{{user}}</i></b></h7></p>
     </div>
 </div>
 <div class="col-sm-4" style="background-color:;">
  <div style="position: relative; left: 0; top: 30%; width: 100%; text-align: center;">
     <img src="https://docs.google.com/uc?id=11gNpuLZuHBRHHiSFZxcSp5CGlJla1PEw" alt="" style="background-color: ;width: 70%">
 </div>
</div>
</div>
<br>
</div>
<hr />

<div class="row">
 <div class="col-sm-5"></div>
 <div class="col-sm-3">Notificações</div>
 <div class="col-sm-4"></div>
</div>            
<table class="table table-hover">
    <thead>
      <tr>
        <th>Data da notificação</th>
        <th>Estabelecimento Solicitante</th>
        <th>Paciente</th>
        <th>Idade</th>
        <th>Ações</th>
        <th>Status</th>
    </tr>
</thead>
<tbody>
   {% for o in regs %}
   <tr>
    {% if o.andamento_processo == 'Cancelado' %}
    <td style="color: #ff0000; font-size: 90%">

        {{o.data_notificacao|date:'d/m/Y'}} - {{o.hora_notificacao|time:'H:i'}}
    </td>
    {%elif o.last_status == 'Obito' %}
    <td style="color: #cc6699; font-size: 90%">

        {{o.data_notificacao|date:'d/m/Y'}} - {{o.hora_notificacao|time:'H:i'}}
    </td>
    {%else%}
    <td style="font-size: 90%">

        {{o.data_notificacao|date:'d/m/Y'}} - {{o.hora_notificacao|time:'H:i'}}
    </td>
    {%endif%}

    {% if o.andamento_processo == 'Cancelado' %}
    <td style="color: #ff0000">
       {% if o.estabelecimento_solicitante == '' or o.estabelecimento_solicitante == None %}
       {{o.estabelecimento_solicitante_outro}}
       {%else%}
       {{o.estabelecimento_solicitante}}
       {%endif%}
   </td>
   {% elif o.last_status == 'Obito' %}
   <td style="color: #cc6699">
    {% if o.estabelecimento_solicitante == '' or o.estabelecimento_solicitante == None %}
    {{o.estabelecimento_solicitante_outro}}
    {%else%}
    {{o.estabelecimento_solicitante}}
    {%endif%}
</td>
{%else%}
<td>
   {% if o.estabelecimento_solicitante == '' or o.estabelecimento_solicitante == None %}
   {% if o.estabelecimento_solicitante_outro == '' or o.estabelecimento_solicitante_outro == None %}
   {%else%}
   {{o.estabelecimento_solicitante_outro}}
   {%endif%}
   {%else%}
   {{o.estabelecimento_solicitante}}
   {%endif%}
</td>
{%endif%}

{% if o.andamento_processo == 'Cancelado' %}
<td><a href="/status_registro/{{o.id}}/" style="color: #ff0000">{{o.nome_paciente}}</a></td>
{% elif o.last_status == 'Obito' %}
<td><a href="/status_registro/{{o.id}}/" style="color: #cc6699">{{o.nome_paciente}}</a></td>
{%else%}
<td><a href="/status_registro/{{o.id}}/">{{o.nome_paciente}}</a></td>
{%endif%}
{% if o.andamento_processo == 'Cancelado' %}
<td style="color: #ff0000">
   {% if o.idade_paciente == '' or o.idade_paciente == None %}
   {%else%}
   {{o.idade_paciente}}
   {%endif%}
</td>
{% elif o.last_status == 'Obito' %}
<td style="color: #cc6699">
    {% if o.idade_paciente == '' or o.idade_paciente == None %}
    {%else%}
    {{o.idade_paciente}}
    {%endif%}
</td>
{%else%}
<td>
   {% if o.idade_paciente == '' or o.idade_paciente == None %}
   {%else%}
   {{o.idade_paciente}}
   {%endif%}
</td>
{%endif%}

{% if o.andamento_processo == 'Cancelado' %}
<td style="font-size: 87%">
   <!--<a href="/regulacao_edit/{{o.id}}">Editar</a>-->
   {% if o.andamento_processo == '' %}
   <a href="/regulacao_search_estabelecimento/{{o.id}}/" style="color: #ff0000">Regular</a>
   {%endif%}
   
   <a href="/regulacao_detail/{{o.id}}/" style="color: #ff0000">Ver</a>

</td>
{% elif o.last_status == 'Obito' %}
<td style="font-size: 87%">
    <!--<a href="/regulacao_edit/{{o.id}}">Editar</a>-->
    
    <a href="/regulacao_detail/{{o.id}}/" style="color: #cc6699">Ver</a>
    

</td>
{%else%}
<td style="font-size: 87%">
   <!--<a href="/regulacao_edit/{{o.id}}">Editar</a>-->
   {% if o.andamento_processo == '' %}
   <a href="/regulacao/{{o.id}}/">Editar</a>
   {%endif%}
   
   <a href="/regulacao_detail/{{o.id}}/">Ver</a>
   

</td>
{%endif%}

{% if o.andamento_processo == 'Cancelado' %}
<td style="color: #ff0000">
   {{o.andamento_processo}}        	
</td>
{%else%}
<td style="font-size: 87%">

   {% if 'Regulado' in o.last_status %}
   <b style="color: #009933">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Não Preenche Critérios' in o.last_status %}
   <b style="color: #993300">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Aguardando confirmação de Vaga' in o.last_status %}
   <b style="color: #666699">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Aguardando em Lista de Espera' in o.last_status %}
   <b style="color: #cccc00">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Obito' in o.last_status %}
   <b style="color: #cc6699">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Aguardando Informações' in o.last_status %}
   <b style="color: #ffb366">{{o.last_status}}<br/></b>
   {%endif%}
   {% if 'Parecer Médico' in o.last_status %}
   <b style="color: #e68a00">{{o.last_status}}<br/></b>
   {%endif%}

</td>
{%endif%}
</tr>
{% endfor %}

</tbody>
</table>

<div style="height: 50px"></div>
<div class="pagination">
 <span class="step-links" style="margin: auto">
   {% if regs.has_previous %}
   <a href="?page={{regs.previous_page_number}}">Anterior</a>
   {% endif %}

   <span class="current">
       {{regs.number}} {% if regs %}de{%else%}{%endif%} {{regs.paginator.num_pages}}
   </span>
   {% if regs.has_next %}
   <a href="?page={{regs.next_page_number}}">Próximo</a>
   {% endif %}

</span>  

</div>


</div><br />


<div style="background-color: #e6e6e6;">

 <br /><br />

</div>

</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login para à CERH :</h1>
<form method="post" action="{% url 'core:user_login' %}">
          {% csrf_token %}
          <label for="username">Usuário:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Senha:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Criar Usuário</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Registrar</button>
  </form>
{% endblock %}